spring:
  thymeleaf:
    mode: HTML
    cache: false
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jason.blog.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

blog:
  comment:
    headPic: /img/per.jpg